# Generated by Django 6.0.1 on 2026-06-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bot_type_user_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
